# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /mymaps
ADD . /mymaps

COPY . /mymaps

RUN pip3 install -r requirements.txt
ENV API_KEY=xxxxxxxxxxxx

EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD [ "mymaps.py" ]
