# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /flogin
ADD . /flogin

COPY . /flogin
RUN pip3 install -r requirements.txt
#RUN python3 manage.py
#ENV FLASK_APP=secondstage1.py  
#ENV FLASK_ENV=development
EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD [ "flogin.py" ]