#% functionReqs(functionId, listOfSWReqs, HWReqs(memory, vCPU, Htz), timeout, listOfServiceReqs(serviceType, latency))
#functionReqs(flogin, [docker], (1024, 2, 500), [(userDB, 13)]).
Deployments:
- Function:
    id: "flogin"
    image: albertosiemanuele/tesitestv1:flogindef
    port: 5000
    exposed: True
    exposed_port: 30006
    is_ingress: True
    type: "branch"
    bindings: 
    - 'myUserDb'
    latfromprev: 25
    links:
    - name: "FUNT"
      btype: 'TRUE'
      next: True
      fun: "fcheckdcc"
      value: "http://fcheckdcc:5000"
    - name: "FUNF"
      next: True
      fun: "frules"
      btype: 'FALSE'
      value: "http://frules:5000"
    - name: "GREENPASSAPI"
      value: "http://greenpassapi:5000"
      next: False 
- Function:
    id: "fcheckdcc"
    image: albertosiemanuele/tesitestv1:fcheckdccdef
    port: 5000
    exposed: False
    is_ingress: False
    type: "node"
    bindings:
    latfromprev: 15
    links:
    - name: "FDCCCHECK"
      value: "http://dccmock:5000"
      next: False
- Function:
    id: "frules"
    image: albertosiemanuele/tesitestv1:frulesdef
    port: 5000
    exposed: False
    is_ingress: False
    type: "node"
    bindings:
    latfromprev: 18
    links:
    - name: "FRULESCHECK"
      value: "http://rulesmock:5000"
      next: False      



###################
EventGenerator:
    generatorId: "userDevice" 
    sectypes:     
    - "top"
    - "low"
    - "medium"

Lattice:
  top: 
    value: "top"
    color: "green"
  intermediate:
  - value: "medium"
    color: "orange"
  bottom: 
      value: "low"
      color: "red"            

NodeSecTypeCaps:
  - label: "top"
    present:
    - "antiTamp"
    - "pubKeyE"
    absent:
  - label: "medium"
    present:
    - "pubKeyE"
    absent:
    - "antiTamp"
  - label: "low"
    present:
    absent:
    - "pubKeyE"
    
ServSecTypes:   
  - label: "top" 
    providers:
    - name: "appOp"
    - name: "pa"
  - label: "medium"
    providers:
    - name: "cloudProvider" 
      serviceType: "maps" 
  - label: "low"
    exclude:
      providers:
        - name: "appOp"  
        - name: "cloudProvider" 
          serviceType: "maps"


##################      

Requirements:
- Function:
    id: "flogin"
    sw:
    - "docker"
    hw:
      mem: 512
      cpu: 1
      mhz: 500
    services:
    - service:
        id: "userDB"
        latency: 13   
#functionReqs(fcrop, [docker], (2048, 4, 1200), []).         
- Function:
    id: "fcheckdcc"
    sw:
    - "docker"
    hw:
      mem: 512
      cpu: 2
      mhz: 500
    services:
    - service:
        id: "checkGp"
        latency: 50 
#functionReqs(frules, [docker], (1800, 1, 400), [(checkRules, 20)]).        
- Function:
    id: "frules"
    sw:
    - "docker"
    hw:
      mem: 512
      cpu: 1
      mhz: 400
    services:
    - service:
        id: "checkRules"
        latency: 20 
#%functionBehaviour(functionId, listOfInputs, listOfun(serviceReq, TypeParam), listOfOutputs)
#functionBehaviour(flogin, [U, Sc, G],[U], [U,Sc, G]).    

Behaviours:
- Function:
    id: "flogin"
    inputs:
    - "U"
    - "Sc"
    - "G"
    fun:
    - "U"
    outputs:
    - "U"
    - "Sc"
    - "G"
    rule:
#functionBehaviour(fcrop,[_,Sc, G],[], [Sc,G]).
- Function:
    id: "fcheckdcc"
    inputs:
    - "U"
    - "_"
    - "_"
    fun:
    - "U"
    outputs:
    - "low"
    rule:
#functionBehaviour(frules, [_, U], [U], [low]).    
- Function:
    id: "frules"
    inputs:
    - "_"
    - "_"
    - "U"
    fun:
    - "U"
    outputs:
    - "low" 
    rule:




