# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /fpadfrulesorder
ADD . /fpadfrulesorder

COPY . /fpadfrulesorder
RUN pip3 install -r requirements.txt

EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD [ "fpadfrulesorder.py" ]
